server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: health-first-server
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/health_first?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Grwpl@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  info:
    title: Health First API
    description: REST API for Health First Provider and Patient Management System
    version: 1.0.0
    contact:
      name: Health First Team
      email: support@healthfirst.com

  # Mail Configuration (for development)
  mail:
    host: localhost
    port: 587
    username: dummy@example.com
    password: dummy
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

# Security Configuration
security:
  jwt:
    secret: ${JWT_SECRET:your-super-secret-jwt-key-here-make-it-very-long-and-secure}
    expiration: 86400000 # 24 hours in milliseconds
  bcrypt:
    salt-rounds: 12

# Logging
logging:
  level:
    com.healthfirst: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 